services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/construction.db
    volumes:
      - backend_data:/app/data
    networks:
      - app-network
    restart: unless-stopped  # Добавлено для автоматического перезапуска

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped  # Добавлено для автоматического перезапуска

volumes:
  backend_data:

networks:
  app-network:
    driver: bridge